### ISSUE TITLE
Building with Yum repo does not work

### ISSUE THREAD

**Issue by bernd** [kisoku/docker-cookery#4]
Looks like the `Repo::Yum#package_exist?` signature is outdated.
```
$ bundle exec docker-cook -d package build clamz centos-6
Tracking build state in stamp_dir: /tmp/docker-cook20150924-18606-1vnicos
initializing apt repo for platform docker-cookery-centos-6
Cleaning up stamp_dir: /tmp/docker-cook20150924-18606-1vnicos
/vagrant/lib/docker-cookery/repo.rb:135:in `package_exist?': wrong number of arguments (2 for 0) (ArgumentError)
	from /vagrant/lib/docker-cookery/package_builder.rb:45:in `wants_to_build?'
	from /vagrant/lib/docker-cookery/package_builder.rb:65:in `block in build'
	from /vagrant/lib/docker-cookery/package_builder.rb:64:in `chdir'
	from /vagrant/lib/docker-cookery/package_builder.rb:64:in `build'
	from /vagrant/lib/docker-cookery/build_manager.rb:41:in `block in build'
	from /vagrant/lib/docker-cookery/build_manager.rb:40:in `each'
	from /vagrant/lib/docker-cookery/build_manager.rb:40:in `build'
	from /vagrant/lib/docker-cookery/cli/package.rb:26:in `exec'
	from /vagrant/lib/docker-cookery/cli/base.rb:16:in `execute'
	from /vagrant/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /vagrant/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /vagrant/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /vagrant/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /vagrant/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /vagrant/vendor/bundle/ruby/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /vagrant/bin/docker-cook:7:in `<top (required)>'
	from /vagrant/vendor/bundle/ruby/2.1.0/bin/docker-cook:23:in `load'
	from /vagrant/vendor/bundle/ruby/2.1.0/bin/docker-cook:23:in `<main>'
```

**Comment by kisoku** [comment]
@bernd any further comments here ?

**Comment by bernd** [comment]
Works after commit 57f9565
